site_name: peptidy

theme:
  name: material
  logo: assets/molml_logo.png
  favicon: assets/molml_logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

repo_url: https://github.com/molML/peptidy/

plugins:
  - mkdocstrings
  - search


markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/style.css

nav:
  - Homepage: index.md
  - API Reference:
    - api/biology.md
    - api/descriptors.md
    - api/encoding.md
    - api/tokenizer.md
  